### ISSUE TITLE
IMPLEMENTATION FOR ios DEVICE

### ISSUE THREAD

**Issue by Rishi341** [perliedman/geojson-path-finder#11]
Really a cool stuff. Wanna implement the same thing for an ios Device. Can this be migrated to Objective - C or Swift language ?. The reason behind is to create a native app. If not , is there any alternative as myself a newbie .

**Comment by perliedman** [comment]
Hi there, unfortunately my experience with native iOS is exactly zero, so I'm sad to say I have no idea. It would theoretically be possible to port the code to just about any language, and probably not too hard, but it would of course require a pretty good understanding of JavaScript.

Closing this, since it's outside the scope of the project.
