### ISSUE TITLE
"Queue is not a constructor" error when bundled with WebPack

### ISSUE THREAD

**Issue by soryy708** [perliedman/geojson-path-finder#71]
If I bundle using Webpack and I `import` this library, when I call `findPath` on an instance of `PathFinder` I get the following error:

> Queue is not a constructor

in the `dijkstra.js` file

**Comment by soryy708** [comment]
I found a workaround: https://github.com/mourner/rbush-knn/issues/18#issuecomment-616130211

Add this to the Webpack config:

```
resolve: {
    alias: {
      "tinyqueue": __dirname + "/node_modules/tinyqueue/tinyqueue.js"
    }
  }
```

**Comment by perliedman** [comment]
Nice! I think this issue comes up a lot when mixing Webpack with CommonJS and ESM. From my understanding, it's really hard to fix on the module author side, so I think your workaround is the best I've seen so far!

I'm closing this, since it seems resolved, but can open again if there's something more that can be done on the module side!
