### ISSUE TITLE
Instructions along with the route

### ISSUE THREAD

**Issue by ShreyasRP** [perliedman/geojson-path-finder#77]
First of all, thanks for this wonderful library!

I was thinking if it was possible to give instructions like walk for 10 metres, turn right, etc. along with the route in the response. If not, is there any other library which gives instructions for a given route?

**Comment by perliedman** [comment]
Hi, and sorry for the late reply. This is not a feature that this library has, and it's not likely it will either. Turning a path into directions is a pretty hard problem (at least to get good results), so I think it's out of scope for what I intended.

Maybe it could be written as a separate module - it would be interesting if someone would like to give it a try.

Closing this for now since like I said I don't think is in geojson-path-finder's scope at the moment.
